package com.test.demo


//Just like java, in Groovy exception handling is done. The good thing about the exception handling
// is even there a exception, it doesn't stop the code execution meaning it executes the code 
// which comes after the exception 


//i =1/0 // There is ArthmeticException when you run this code.To handle this type of Exceptions, you can add the some code to handle it
	// This is where try-catch in to picture 

//try-catch-finally
//try-finally


//try-catch
//Once there is a errors, it executes the exception block and prints the message

try {
int i =1/0
}catch(Exception exp) {
	println "I'm inside the exception block"
	println exp.getCause()
	println exp.getMessage() //it will show you the message
	exp.printStackTrace() //it will give detailed information fo the exception
}

println "Another set of code"



// Can have multiple try catch exceptions.

try {
	int i =1/0
	}catch(ArithmeticException exp1) {
		println "Catch Block to catch Arithmetic exp"
	}
	
catch(Exception exp) {
		println "I'm inside the exception block"
		println exp.getCause()
		println exp.getMessage() //it will show you the message
		exp.printStackTrace() //it will give detailed information fo the exception
	}finally {
		println "I'm inside the finally block"
	}
	
	println "Another set of code"


